### ISSUE TITLE
v0.6 Moving nodes changes generated patterns 

### ISSUE THREAD

**Issue by moseseribo** [RodZill4/godot-procedural-textures#15]
In this example when moving the voronoi node the generated texture changes.

![material_maker_DrcZ3yosSA](https://user-images.githubusercontent.com/24284283/66961825-6cd97880-f067-11e9-8a92-2806956bc64e.png)
![material_maker_HbJ3yi932D](https://user-images.githubusercontent.com/24284283/66961826-6cd97880-f067-11e9-90e7-996c4d12ae66.png)

**Comment by jackaperkins** [comment]
As I understand, this is an intended feature, using the screen position of the node as the "Seed"

If we were to improve this, how could we? Maybe a special re-seed button on any node that is random based, so the user can click it to regenerate, and so that re-arranging the nodes doesn't destroy the current seed?

**Comment by RodZill4** [comment]
Yes this is intended. I think a "lock seed" button would help in case you want  to keep the current aspect of a node, and I would also like to do something about how subgraphs affect their children's seeds. Not sure how yet...

**Comment by RodZill4** [comment]
Seed lock and inheritance are now implemented.
